export interface CompanyProfile {
  id: string;
  name: string;
  logoUrl?: string;
  description: string;
  keywords: string[];
  weightings: Record<string, number>; // keyword -> weight (1.0 to 3.0)
  cultureKeywords: string[];
  passingScore: number;
}

export interface JobRoleProfile {
  id: string;
  title: string;
  category: string;
  requiredSkills: string[];
  recommendedKeywords: string[];
}

export const TARGET_JOB_ROLES: JobRoleProfile[] = [
  {
    id: "software-engineer",
    title: "Software Engineer",
    category: "Engineering",
    requiredSkills: [
      "Data Structures",
      "Algorithms",
      "System Design",
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "Git",
      "REST API",
      "SQL",
      "Unit Testing",
      "CI/CD",
    ],
    recommendedKeywords: [
      "scalability",
      "optimization",
      "microservices",
      "code quality",
      "agile",
      "cloud",
      "docker",
      "kubernetes",
      "distributed systems",
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    category: "Data & AI",
    requiredSkills: [
      "Python",
      "R",
      "Machine Learning",
      "Deep Learning",
      "SQL",
      "Pandas",
      "NumPy",
      "Scikit-Learn",
      "TensorFlow",
      "PyTorch",
      "Statistics",
      "Data Visualization",
    ],
    recommendedKeywords: [
      "predictive modeling",
      "A/B testing",
      "feature engineering",
      "NLP",
      "big data",
      "spark",
      "tableau",
      "power bi",
      "clustering",
      "regression",
    ],
  },
  {
    id: "product-manager",
    title: "Product Manager",
    category: "Product",
    requiredSkills: [
      "Product Strategy",
      "Roadmapping",
      "User Research",
      "Agile/Scrum",
      "KPIs",
      "A/B Testing",
      "Wireframing",
      "Data Analytics",
      "Stakeholder Management",
      "SQL",
    ],
    recommendedKeywords: [
      "user centric",
      "go to market",
      "prioritization",
      "product lifecycle",
      "conversion rate",
      "retention",
      "customer feedback",
      "cross functional",
    ],
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    category: "Infrastructure",
    requiredSkills: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "AWS",
      "Azure",
      "CI/CD",
      "Jenkins",
      "Linux",
      "Bash",
      "Python",
      "Prometheus",
      "Grafana",
    ],
    recommendedKeywords: [
      "infrastructure as code",
      "automation",
      "monitoring",
      "scalability",
      "high availability",
      "disaster recovery",
      "security",
      "helm",
    ],
  },
  {
    id: "fullstack-developer",
    title: "Full Stack Developer",
    category: "Engineering",
    requiredSkills: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Express",
      "MongoDB",
      "PostgreSQL",
      "REST API",
      "GraphQL",
      "Tailwind CSS",
      "Git",
    ],
    recommendedKeywords: [
      "frontend",
      "backend",
      "database architecture",
      "responsive design",
      "serverless",
      "state management",
      "web security",
    ],
  },
  {
    id: "aiml-engineer",
    title: "AI/ML Engineer",
    category: "Data & AI",
    requiredSkills: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "LLMs",
      "LangChain",
      "Transformers",
      "Vector Databases",
      "Model Deployment",
      "Docker",
      "API Integration",
    ],
    recommendedKeywords: [
      "generative ai",
      "fine tuning",
      "rag",
      "embeddings",
      "neural networks",
      "model optimization",
      "prompt engineering",
      "mlops",
    ],
  },
  {
    id: "data-analyst",
    title: "Data Analyst",
    category: "Data & AI",
    requiredSkills: [
      "SQL",
      "Excel",
      "Tableau",
      "Power BI",
      "Python",
      "Pandas",
      "Data Cleaning",
      "Reporting",
      "Business Intelligence",
    ],
    recommendedKeywords: [
      "dashboard",
      "insights",
      "data integrity",
      "metrics",
      "trend analysis",
      "cohort analysis",
      "data pipeline",
    ],
  },
  {
    id: "cloud-architect",
    title: "Cloud Architect",
    category: "Infrastructure",
    requiredSkills: [
      "AWS",
      "Azure",
      "GCP",
      "Cloud Security",
      "Microservices",
      "Networking",
      "Terraform",
      "Cost Optimization",
      "System Architecture",
    ],
    recommendedKeywords: [
      "cloud native",
      "disaster recovery",
      "compliance",
      "migration",
      "serverless architecture",
      "hybrid cloud",
    ],
  },
];

export const TARGET_COMPANIES: CompanyProfile[] = [
  {
    id: "google",
    name: "Google",
    description: "Focuses heavily on algorithmic excellence, scale, data structures, and systemic impact.",
    keywords: [
      "algorithms",
      "data structures",
      "system design",
      "distributed systems",
      "scalability",
      "python",
      "c++",
      "java",
      "go",
      "machine learning",
      "cloud",
      "code review",
      "latency",
      "optimization",
      "big query",
      "gcp",
    ],
    weightings: {
      "algorithms": 3.0,
      "system design": 3.0,
      "distributed systems": 2.5,
      "scalability": 2.5,
      "data structures": 2.8,
      "optimization": 2.0,
      "gcp": 2.0,
      "python": 2.0,
      "c++": 2.0,
      "latency": 2.2,
    },
    cultureKeywords: ["googleyness", "data-driven", "innovative", "user-first", "impact at scale"],
    passingScore: 82,
  },
  {
    id: "amazon",
    name: "Amazon",
    description: "Evaluates leadership principles, operational excellence, AWS cloud, and customer obsession.",
    keywords: [
      "aws",
      "leadership principles",
      "customer obsession",
      "ownership",
      "bias for action",
      "deliver results",
      "microservices",
      "java",
      "python",
      "dynamodb",
      "lambda",
      "scalability",
      "metrics",
      "operational excellence",
      "cloud computing",
    ],
    weightings: {
      "aws": 3.0,
      "customer obsession": 2.8,
      "ownership": 2.5,
      "bias for action": 2.5,
      "microservices": 2.5,
      "metrics": 2.2,
      "operational excellence": 2.4,
      "java": 2.0,
      "deliver results": 2.3,
    },
    cultureKeywords: ["frugality", "invent and simplify", "deep dive", "earn trust", "insist on highest standards"],
    passingScore: 80,
  },
  {
    id: "microsoft",
    name: "Microsoft",
    description: "Values enterprise software reliability, Azure cloud, growth mindset, and clean architecture.",
    keywords: [
      "azure",
      "c#",
      ".net",
      "typescript",
      "react",
      "cloud architecture",
      "sql server",
      "devops",
      "ci/cd",
      "unit testing",
      "enterprise solutions",
      "growth mindset",
      "collaboration",
      "microservices",
      "security",
    ],
    weightings: {
      "azure": 3.0,
      "c#": 2.5,
      ".net": 2.5,
      "typescript": 2.2,
      "cloud architecture": 2.6,
      "devops": 2.2,
      "growth mindset": 2.0,
      "security": 2.4,
      "enterprise solutions": 2.3,
    },
    cultureKeywords: ["growth mindset", "diversity & inclusion", "customer-centric", "empowerment"],
    passingScore: 78,
  },
  {
    id: "tcs",
    name: "TCS (Tata Consultancy Services)",
    description: "Emphasis on structured methodologies, Agile delivery, client projects, and domain skills.",
    keywords: [
      "java",
      "python",
      "sql",
      "agile",
      "scrum",
      "client communication",
      "sdlc",
      "software development",
      "database management",
      "testing",
      "cloud",
      "devops",
      "api development",
      "problem solving",
      "documentation",
    ],
    weightings: {
      "agile": 2.8,
      "java": 2.5,
      "sql": 2.5,
      "sdlc": 2.4,
      "client communication": 2.2,
      "testing": 2.2,
      "python": 2.0,
      "documentation": 2.0,
    },
    cultureKeywords: ["integrity", "excellence", "responsibility", "client trust"],
    passingScore: 72,
  },
  {
    id: "infosys",
    name: "Infosys",
    description: "Focuses on continuous learning, digital transformation, modern tech stacks, and team collaboration.",
    keywords: [
      "java",
      "spring boot",
      "react",
      "angular",
      "sql",
      "rest api",
      "microservices",
      "agile",
      "cloud",
      "full stack",
      "automation",
      "git",
      "unit testing",
      "problem solving",
      "digital transformation",
    ],
    weightings: {
      "java": 2.6,
      "spring boot": 2.5,
      "microservices": 2.5,
      "react": 2.2,
      "rest api": 2.4,
      "agile": 2.3,
      "digital transformation": 2.0,
    },
    cultureKeywords: ["continuous learning", "innovation", "client success", "leadership"],
    passingScore: 70,
  },
  {
    id: "accenture",
    name: "Accenture",
    description: "Looks for technology consulting skills, cloud delivery, agile transformation, and business value.",
    keywords: [
      "cloud migration",
      "agile",
      "stakeholder management",
      "system integration",
      "devops",
      "python",
      "java",
      "aws",
      "azure",
      "sap",
      "salesforce",
      "data analytics",
      "automation",
      "consulting",
      "client delivery",
    ],
    weightings: {
      "cloud migration": 2.8,
      "agile": 2.6,
      "stakeholder management": 2.5,
      "consulting": 2.4,
      "devops": 2.2,
      "aws": 2.3,
      "azure": 2.3,
      "client delivery": 2.2,
    },
    cultureKeywords: ["360 value", "inclusion & diversity", "technological innovation"],
    passingScore: 74,
  },
  {
    id: "jpmorgan",
    name: "JP Morgan Chase",
    description: "Demands high-concurrency backend architecture, financial systems security, low latency, and robust risk management.",
    keywords: [
      "java",
      "spring boot",
      "python",
      "c++",
      "sql",
      "kafka",
      "microservices",
      "low latency",
      "distributed systems",
      "multithreading",
      "financial modeling",
      "risk management",
      "cybersecurity",
      "rest api",
      "cloud",
      "unit testing",
    ],
    weightings: {
      "java": 3.0,
      "spring boot": 2.8,
      "kafka": 2.6,
      "low latency": 2.8,
      "microservices": 2.6,
      "multithreading": 2.7,
      "cybersecurity": 2.4,
      "risk management": 2.2,
    },
    cultureKeywords: ["operational integrity", "risk control", "customer trust", "financial rigor"],
    passingScore: 80,
  },
];
