"use client";

import React, { useState } from "react";
import {
  CheckCircle,
  AlertTriangle,
  Lightbulb,
  Briefcase,
  Copy,
  Check,
  Sparkles,
  Download,
  TrendingUp,
} from "lucide-react";

interface AlternativeRole {
  title: string;
  matchPercent: number;
  reason: string;
}

interface InsightsViewProps {
  strengths: string[];
  weaknesses: string[];
  actionableSuggestions: string[];
  bestFitAlternativeRoles: AlternativeRole[];
  targetRoleTitle: string;
  targetCompanyName: string;
  overallScore: number;
}

export const InsightsView: React.FC<InsightsViewProps> = ({
  strengths,
  weaknesses,
  actionableSuggestions,
  bestFitAlternativeRoles,
  targetRoleTitle,
  targetCompanyName,
  overallScore,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyReport = () => {
    const reportText = `AI Resume Analysis Report
Target Role: ${targetRoleTitle}
Target Company: ${targetCompanyName}
Overall ATS Score: ${overallScore}/100

STRENGTHS:
${strengths.map((s) => `• ${s}`).join("\n")}

WEAKNESSES / GAPS:
${weaknesses.map((w) => `• ${w}`).join("\n")}

ACTIONABLE IMPROVEMENT SUGGESTIONS:
${actionableSuggestions.map((a, i) => `${i + 1}. ${a}`).join("\n")}

TOP BEST-FIT ALTERNATIVE ROLES:
${bestFitAlternativeRoles
  .map((r) => `• ${r.title} (${r.matchPercent}% Match) - ${r.reason}`)
  .join("\n")}
`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadReport = () => {
    const reportText = `AI Resume Analysis Report
Generated by ResumePulse AI

Target Role: ${targetRoleTitle}
Target Company: ${targetCompanyName}
Overall ATS Score: ${overallScore}/100

==================================================
1. STRENGTHS
==================================================
${strengths.map((s) => `• ${s}`).join("\n")}

==================================================
2. WEAKNESSES / ATS GAPS
==================================================
${weaknesses.map((w) => `• ${w}`).join("\n")}

==================================================
3. ACTIONABLE IMPROVEMENT SUGGESTIONS
==================================================
${actionableSuggestions.map((a, i) => `${i + 1}. ${a}`).join("\n")}

==================================================
4. TOP BEST-FIT ALTERNATIVE ROLES
==================================================
${bestFitAlternativeRoles
  .map((r) => `• ${r.title} (${r.matchPercent}% Match) - ${r.reason}`)
  .join("\n")}
`;

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Resume_ATS_Analysis_${targetCompanyName}_${targetRoleTitle.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header action bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-2xl glass-panel p-4 border border-gray-800">
        <div className="flex items-center space-x-2">
          <Sparkles className="h-5 w-5 text-indigo-400" />
          <h2 className="text-base font-bold text-white">AI-Powered Insights & Guidance</h2>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopyReport}
            className="flex items-center space-x-1.5 rounded-lg bg-gray-900 px-3 py-1.5 text-xs font-semibold text-gray-300 hover:bg-gray-800 hover:text-white border border-gray-800 transition-all"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? "Copied Report!" : "Copy Report"}</span>
          </button>
          <button
            onClick={handleDownloadReport}
            className="flex items-center space-x-1.5 rounded-lg bg-indigo-600/20 px-3 py-1.5 text-xs font-semibold text-indigo-300 hover:bg-indigo-600/30 border border-indigo-500/30 transition-all"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download TXT</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* 1. Strengths */}
        <div className="rounded-2xl glass-panel p-6 border border-emerald-500/20 bg-emerald-950/10 space-y-4">
          <div className="flex items-center space-x-2 border-b border-emerald-500/20 pb-3">
            <CheckCircle className="h-5 w-5 text-emerald-400" />
            <h3 className="text-sm font-bold text-white">Key Resume Strengths</h3>
          </div>
          <ul className="space-y-2.5 text-xs text-gray-300">
            {strengths.map((strength, index) => (
              <li key={index} className="flex items-start space-x-2">
                <span className="mt-1 h-1.5 w-1.5 rounded-full bg-emerald-400 shrink-0"></span>
                <span>{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* 2. Weaknesses */}
        <div className="rounded-2xl glass-panel p-6 border border-rose-500/20 bg-rose-950/10 space-y-4">
          <div className="flex items-center space-x-2 border-b border-rose-500/20 pb-3">
            <AlertTriangle className="h-5 w-5 text-rose-400" />
            <h3 className="text-sm font-bold text-white">Gaps & Missing Keywords</h3>
          </div>
          <ul className="space-y-2.5 text-xs text-gray-300">
            {weaknesses.map((weakness, index) => (
              <li key={index} className="flex items-start space-x-2">
                <span className="mt-1 h-1.5 w-1.5 rounded-full bg-rose-400 shrink-0"></span>
                <span>{weakness}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* 3. Actionable Improvement Suggestions (3-5 items) */}
      <div className="rounded-2xl glass-panel p-6 border border-amber-500/20 bg-amber-950/10 space-y-4">
        <div className="flex items-center space-x-2 border-b border-amber-500/20 pb-3">
          <Lightbulb className="h-5 w-5 text-amber-400" />
          <h3 className="text-sm font-bold text-white">Actionable Improvement Suggestions</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {actionableSuggestions.map((suggestion, index) => (
            <div
              key={index}
              className="rounded-xl bg-gray-900/60 p-3.5 border border-amber-500/10 flex items-start space-x-3"
            >
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-amber-500/20 text-xs font-bold text-amber-300 shrink-0">
                {index + 1}
              </span>
              <p className="text-xs text-gray-300 leading-relaxed">{suggestion}</p>
            </div>
          ))}
        </div>
      </div>

      {/* 4. Top 3 Best-Fit Alternative Roles */}
      <div className="rounded-2xl glass-panel p-6 border border-indigo-500/20 bg-indigo-950/10 space-y-4">
        <div className="flex items-center space-x-2 border-b border-indigo-500/20 pb-3">
          <Briefcase className="h-5 w-5 text-indigo-400" />
          <h3 className="text-sm font-bold text-white">Top 3 Best-Fit Alternative Roles</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {bestFitAlternativeRoles.map((role, index) => (
            <div
              key={index}
              className="rounded-xl bg-gray-900/80 p-4 border border-gray-800 space-y-2 flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-white">{role.title}</h4>
                  <span className="inline-flex items-center gap-0.5 rounded-full bg-indigo-500/20 px-2 py-0.5 text-[10px] font-bold text-indigo-300 border border-indigo-500/30">
                    <TrendingUp className="h-3 w-3 text-indigo-400" /> {role.matchPercent}% Match
                  </span>
                </div>
                <p className="text-[11px] text-gray-400 mt-2 leading-relaxed">{role.reason}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
